[build]
builder = "dockercompose"
dockerComposeFile = "docker-compose.yml"

[deploy]
restartPolicyType = "on_failure"

[environments.production.variables]
ENVIRONMENT = "production"
MONGODB_URL = "mongodb://mongo:27017/product_tracking"
