services:
  # Backend API Service
  - type: web
    name: product-tracker-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: JWT_SECRET_KEY
        generateValue: true
    healthCheckPath: /health

  # Frontend Web Service  
  - type: web
    name: product-tracker-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: product-tracker-backend
          property: host
      - key: REACT_APP_LOGIN_USERNAME
        value: user_name_placeholder
      - key: REACT_APP_LOGIN_PASSWORD
        value: password_placeholder
